#!/usr/bin/env node

/*

This is a helper forwarding commands to packages/abc-cli/build/main.js

 */

import path from 'path';
import fs from 'fs/promises';
import { exec, execSync } from 'child_process';
import util from 'util';
const execPromise = util.promisify(exec);

const NodeVersionMin = 22;
const ProjectRoot = path.resolve(import.meta.dirname);
const CliRoot = path.resolve(ProjectRoot, 'packages/abc-cli');
const CliMain = path.resolve(CliRoot, 'build', 'main.js');
const RootNodeModules = path.resolve(CliRoot, 'node_modules');
const CliNodeModules = path.resolve(CliRoot, 'node_modules');
const LastCommitBuiltFile = path.resolve(CliRoot, '.last-commit-built.txt');

main(process.argv)
  .then(() => {
    process.exit(0);
  })
  .catch((err) => {
    if (isDebug()) {
      console.error(err);
    } else {
      console.error(err.message);
    }

    process.exit(1);
  });

async function main(args) {
  const [, , cliIsUpToDate] = await Promise.all([checkNodeVersion(), checkPrerequisites(), isCliUpToDate()]);

  if (!cliIsUpToDate) {
    await updateCli();
  }

  abcCliCommand(args);
}

async function checkNodeVersion() {
  const output = await execPromise('node -v', { cwd: CliRoot, stdio: 'pipe' });
  const versionMatch = output.stdout.toString('utf-8').match(/^v([0-9]+)/);
  const version = versionMatch && versionMatch.length && parseInt(versionMatch[1]);

  if (!version || version < NodeVersionMin) {
    throw new Error(`Please use at least Node.js ${NodeVersionMin}`);
  }
}

async function checkPrerequisites() {
  const tools = [{ name: 'pnpm', doc: 'https://pnpm.io/fr/installation' }];
  for (const tool of tools) {
    try {
      await execPromise('command -v ' + tool.name);
    } catch (err) {
      throw new Error('You must install "' + tool.name + '", see: ' + tool.doc);
    }
  }
}

async function isCliUpToDate() {
  if (isContinuousIntegration()) {
    return false;
  }

  const nodeModulesExists = (await isDirectory(CliNodeModules)) && (await isDirectory(RootNodeModules));
  const cliMainExists = await isFile(CliMain);
  const lastCommitBuiltExists = await isFile(LastCommitBuiltFile);

  if (!nodeModulesExists || !cliMainExists || !lastCommitBuiltExists) {
    return false;
  }

  const currentCommit = await getCliLastCommit();
  const lastCommitBuilt = (await fs.readFile(LastCommitBuiltFile)).toString('utf-8').trim();

  const upToDate = currentCommit === lastCommitBuilt;
  if (isDebug()) {
    console.log('CLI build status: ' + JSON.stringify({ upToDate, currentCommit, lastCommitBuilt }));
  }

  return upToDate;
}

async function updateCli() {
  console.log('\n🔨 Abc CLI must be initialized, it may take a few minutes ... 🔧\n');

  // We use sync to show outputs in a convenient way
  execSync('pnpm install -f', { cwd: ProjectRoot, stdio: 'inherit' });
  execSync('pnpm run clean-build', { cwd: CliRoot, stdio: 'inherit' });

  const currentCommit = await getCliLastCommit();
  await fs.writeFile(LastCommitBuiltFile, currentCommit);

  console.log('\n');
}

function isContinuousIntegration() {
  return process.env.CI === 'true';
}

function abcCliCommand(args) {
  const argsStr = args.slice(2).join(' ');
  // We use sync to show outputs in a convenient way
  execSync(`node ${CliMain} ${argsStr}`, { cwd: process.cwd(), stdio: 'inherit' });
}

async function getCliLastCommit() {
  const output = await execPromise(`git rev-list HEAD -- packages/abc-cli | head -1`, { cwd: ProjectRoot });
  if (!output.stdout) {
    throw new Error('Invalid stdout: ' + JSON.stringify(output));
  }
  return output.stdout.toString().trim();
}

function isDirectory(path) {
  return fs
    .stat(path)
    .then((s) => s.isDirectory())
    .catch(() => false);
}

function isFile(path) {
  return fs
    .stat(path)
    .then((s) => s.isFile())
    .catch(() => false);
}

function isDebug() {
  return process.env.DEBUG === 'true';
}
