version: '3.1'

##
## TODO: Add autoheal
## TODO: Variabilize passwords with env vars
##
##

services:

  abcmap-mainapp:
    container_name: abcmap-mainapp
    restart: always
    build: .
    networks:
      - abcmap
    ports:
      - "80:32158"
    environment:
      ABC_MONGODB_HOST: abcmap-mongodb
      ABC_MINIO_HOST: abcmap-minio

  abcmap-mongodb:
    image: mongo:4-xenial
    container_name: abcmap-mongodb
    restart: always
    networks:
      - abcmap
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - './data/mongodb-data:/data/db'
    command: mongod

  abcmap-minio:
    image: minio/minio:RELEASE.2019-04-18T21-44-59Z
    container_name: abcmap-minio
    restart: always
    volumes:
      - './data/minio-data/data1:/data'
    networks:
      - abcmap
    ports:
      - "127.0.0.1:9001:9000"
    environment:
      MINIO_ACCESS_KEY: fb37ca0b53f49587c534be53281a9f94a865d6cedb1e205c1f057810
      MINIO_SECRET_KEY: ea6dd22b3cd0c3908b0e59c4e769a0abff1c4d0081585fa5ea6dd22b3cd0c3908b0e59c4e769a0abff1c4d0081585fa5
    command: server /data

networks:
  abcmap:
