packages:
  - .
  - documentation
  - packages/**

allowBuilds:
  canvas: true
  core-js: true
  cypress: true
  esbuild: true
  sharp: true

# In order to prevent supply chain attacks, we disable git and tgz sub dependencies.
# See https://pnpm.io/supply-chain-security#block-risky-postinstall-scripts
blockExoticSubdeps: true

# In order to prevent supply chain attacks, we ensure that versions are more than one week old.
# See https://pnpm.io/supply-chain-security#delay-dependency-updates
minimumReleaseAge: 10080

storeDir: .pnpm-store
