{{- if .Values.mongoexpress.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "abc-map.fullname" . }}-mongoexpress
  labels:
    {{- include "abc-map.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: mongoexpress
      protocol: TCP
      name: mongoexpress
  selector:
    app.kubernetes.io/name: {{ include "abc-map.name" . }}-mongoexpress
    app.kubernetes.io/instance: {{ .Release.Name }}-mongoexpress
  {{- end }}
