{{- if .Values.mongodb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "abc-map.fullname" . }}-mongodb
  labels:
    {{- include "abc-map.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "abc-map.name" . }}-mongodb
      app.kubernetes.io/instance: {{ .Release.Name }}-mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "abc-map.name" . }}-mongodb
        app.kubernetes.io/instance: {{ .Release.Name }}-mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.auth.rootUsername }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.auth.rootPassword }}
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data/db

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.persistence.existingClaim }}

      {{- with .Values.mongodb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.mongodb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.mongodb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  {{- end }}
