
version: 2
jobs:
  build:
    docker:
      - image: remipassmoilesel/nodejs-build:0.2

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx512m
      SPRING_PROFILES_ACTIVE: test

    steps:
      - checkout
      - restore_cache:
          keys:
            - main-dependencies

      - run: ./.circleci/run.sh

      - save_cache:
          paths:
            - ~/.npm
          key: main-dependencies
