# Copyright © 2021 Rémi Pace.
# This file is part of Abc-Map.
#
# Abc-Map is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Abc-Map is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General
# Public License along with Abc-Map. If not, see <https://www.gnu.org/licenses/>.

storage: /tmp/verdaccio-storage
# We must use "127.0.0.1" and not localhost here, otherwise start may fail on some OS
listen: 127.0.0.1:4873
max_body_size: 50mb
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@abc-map/*':
    access: $all
    publish: $all
  '**':
    access: $all
    publish: $all
    proxy: npmjs
middlewares:
  audit:
    enabled: false
logs:
  - { type: stdout, format: pretty, level: http }
