export enum StyleProperties {
  FillPattern = 'abc:style:fill:pattern',
  FillColor1 = 'abc:style:fill:color1',
  FillColor2 = 'abc:style:fill:color2',
  StrokeColor = 'abc:style:stroke:color',
  StrokeWidth = 'abc:style:stroke:width',
  TextValue = 'abc:style:text:value',
  TextColor = 'abc:style:text:color',
  TextSize = 'abc:style:text:size',
  TextFont = 'abc:style:text:font',
  TextOffsetX = 'abc:style:text:offset-x',
  TextOffsetY = 'abc:style:text:offset-y',
  TextAlignment = 'abc:style:text:alignment',
  PointSize = 'abc:style:point:size',
}
