version: '3.1'

services:

  mongo:
    image: mongo
    container_name: abcmap-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - './mongodb-data:/data/db'

  mongo-express:
    image: mongo-express
    container_name: abcmap-mongodb-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  minio1:
    image: minio/minio:RELEASE.2019-04-18T21-44-59Z
    container_name: abcmap-minio
    restart: always
    volumes:
      - './minio-data/data1:/data'
    ports:
      - 9001:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

