
- name: "Copy source directory"
  synchronize:
    src: "{{ abcmap.rootDir }}"
    dest: "{{ abcmap.destination }}"
    delete: yes
    rsync_opts:
      - "--exclude='/data/**/*'"
      - "--exclude='/deployment/dev-databases/**/*'"
