
- set_fact:
    packages:
      - docker.io
      - python-pip

- name: "Install Docker"
  apt: name={{ packages }} state=present

- name: "Ensure pip is up to date"
  pip:
    name: pip
    state: latest

- name: "Install docker-compose"
  pip:
    name: docker-compose
