export enum Command {
  INSTALL = 'install',
  LINT = 'lint',
  BUILD = 'build',
  TEST = 'test',
  E2E = 'e2e',
  WATCH = 'watch',
  CI = 'ci',
  START = 'start',
  START_SERVICES = 'start-services',
  STOP_SERVICES = 'stop-services',
  CLEAN_RESTART_SERVICES = 'clean-restart-services',
  CLEAN = 'clean',
  DEPENDENCY_CHECK = 'dep-check',
  HELP = 'help',
}
