systemLog:
   destination: file
   path: "logs/mongod.log"
   logAppend: false
   verbosity: 1 # 0 > 5, 5 is the more verbose
   traceAllExceptions: true
storage:
   dbPath: mongodb-data/
   journal:
      enabled: true
processManagement:
   fork: false
net:
   bindIp: 127.0.0.1
   port: 27017
setParameter:
   enableLocalhostAuthBypass: true