
- name: "Restart application"
  shell: "time docker-compose up -d --remove-orphans --force-recreate --build | tee -a /var/log/abcmap.start.log"
  args:
    executable: /bin/bash
    chdir: "{{ abcmap.destination }}"
