- hosts: all
  vars_files:
    - variables.yml
  roles:
    - {name: setup-docker,              tags: [ prerequisites ]}
    - {name: synchronize-sources,       tags: [ fast-update ]}
    - {name: start-application,         tags: [ fast-update ]}
    - {name: check-application-health,  tags: [ fast-update ]}
