- hosts: all
  vars_files:
    - variables.yml
  roles:
    - {name: setup-sshd,                tags: [ prerequisites ]}
    - {name: setup-prerequisites,       tags: [ prerequisites ]}
    - {name: setup-docker,              tags: [ prerequisites ]}
    - {name: setup-nodejs,              tags: [ prerequisites ]}
    - {name: synchronize-sources,       tags: [ fast-update ]}
    - {name: build-application,         tags: [ fast-update ]}
    - {name: start-application,         tags: [ fast-update ]}
    - {name: check-application-health,  tags: [ fast-update ]}
